### ISSUE TITLE
Difference with `elm-codegen`

### ISSUE THREAD

**Issue by kutyel** [lue-bird/generate-elm#1]
Looks like this is a similar project to https://github.com/mdgriffith/elm-codegen but I want to understand the similarities/differentes to see whether of those could generate the desired elm-monocle lenses I want 🙏🏻

**Comment by lue-bird** [comment]
I killed the custom code generation part of this project because elm-codegen was very close to my vision.
I might revive this as an `elm-codegen` in `elm-review` integration
but this will take time.

So for now [`lue-bird/elm-review-missing-record-field-lens`](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-missing-record-field-lens/latest/) + [`the-sett/elm-syntax-dsl`](https://dark.elm.dmy.fr/packages/the-sett/elm-syntax-dsl/latest/) is still the thing to reach for to _automatically_ generate lenses based on use.

`elm-codegen` is very good for generation but you have to run it explicitly each time.
If that's what you want, `elm-codegen` is your tool

**Comment by kutyel** [comment]
Awesome, thanks!
